name: Build Release

on:  
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
  publish_binaries:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: cg-gen-events
      uses: wangyoucao577/go-release-action@v1.28
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        asset_name: cg-gen-events-${{matrix.goos}}-${{matrix.goarch}}
        extra_files: LICENSE README.md
        ldflags: -X "main.version=${{ github.ref_name }}"
        md5sum: false
        project_path: ./cmd/cg-gen-events
        binary_name: cg-gen-events
    - name: cge-ls
      uses: wangyoucao577/go-release-action@v1.28
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        asset_name: cge-ls-${{matrix.goos}}-${{matrix.goarch}}
        extra_files: LICENSE cmd/cge-ls/README.md
        ldflags: -X "main.version=${{ github.ref_name }}"
        md5sum: false
        project_path: ./cmd/cge-ls
        binary_name: cge-ls
